include Makefile.include/variables.mk
include Makefile.include/run_zombietest.mk
include Makefile.include/polkadot.mk
include Makefile.include/zombie_tester.mk
include Makefile.include/zombietests.mk
