[settings]
timeout = 1000

[relaychain.genesis.runtimeGenesis.patch.configuration.config]
  needed_approvals = 8

[relaychain.genesis.runtimeGenesis.patch.configuration.config.scheduler_params]
  max_validators_per_core = 5

[relaychain.genesis.runtimeGenesis.patch.configuration.config.approval_voting_params]
  max_approval_coalesce_count = 5


[relaychain]
chain = "rococo-local"
default_command = "polkadot"

[relaychain.default_resources]
limits = { memory = "4G", cpu = "2" }
requests = { memory = "2G", cpu = "1" }

  [[relaychain.nodes]]
  name = "alice"
  command = "malus dispute-ancestor --fake-validation approval-invalid"
  args = [ "--alice", " -lparachain=debug,MALUS=trace" ]

  [[relaychain.nodes]]
  name = "bob"
  command = "malus dispute-ancestor --fake-validation approval-invalid"
  args = [ "--bob", "-lparachain=debug,MALUS=trace"]

  [[relaychain.nodes]]
  name = "charlie"
  command = "kagome"
  prometheus_prefix = "kagome"
  args = [ "--charlie", "-lparachain=debug", "--wasm-execution Compiled"]

  [[relaychain.nodes]]
  name = "dave"
  command = "kagome"
  prometheus_prefix = "kagome"
  args = [ "--dave", "-lparachain=debug", "--wasm-execution Compiled"]

  [[relaychain.nodes]]
  name = "ferdie"
  args = [ "--ferdie", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "eve"
  args = [ "--eve", "-lparachain=debug"]

  [[relaychain.nodes]]
  name = "one"
  args = [ "--one", "-lparachain=debug" ]

  [[relaychain.nodes]]
  name = "two"
  args = [ "--two", "-lparachain=debug"]

{% for id in range(2000,2004) %}
[[parachains]]
id = {{id}}
addToGenesis = true
genesis_state_generator = "undying-collator export-genesis-state --pov-size={{25000*(id-1999)}} --pvf-complexity={{id - 1999}}"

  [parachains.collator]
  name = "collator"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size={{25000*(id-1999)}}", "--parachain-id={{id}}", "--pvf-complexity={{id - 1999}}"]

{% endfor %}

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
