[settings]
timeout = 1000
bootnode = true

[relaychain.genesis.runtimeGenesis.patch.configuration.config]
  needed_approvals = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.scheduler_params]
  max_validators_per_core = 1
  group_rotation_frequency = 10

[relaychain]
chain = "westend-local" # for the disabling to take an effect
default_command = "polkadot"

[relaychain.default_resources]
limits = { memory = "4G", cpu = "2" }
requests = { memory = "2G", cpu = "1" }

  [[relaychain.node_groups]]
  name = "honest-validator"
  count = 2
  args = ["-lparachain=debug"]

  [[relaychain.node_groups]]
  name = "kagome-honest-validator"
  command = "kagome"
  prometheus_prefix = "kagome"
  count = 1
  args = ["-lparachain=debug", "--wasm-execution=Compiled"]

  [[relaychain.node_groups]]
  name = "malus-validator"
  command = "malus suggest-garbage-candidate"
  args = ["-lMALUS=trace"]
  count = 1

[[parachains]]
id = 1000
cumulus_based = true

  [parachains.collator]
  name = "alice"
  command = "polkadot-parachain"
  args = ["-lparachain=debug"]
