[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"

[relaychain.genesis.runtimeGenesis.patch.configuration.config]
  needed_approvals = 4
  relay_vrf_modulo_samples = 6

[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
  max_candidate_depth = 3
  allowed_ancestry_len = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.scheduler_params]
  lookahead = 2
  group_rotation_frequency = 4


[relaychain.default_resources]
limits = { memory = "4G", cpu = "2" }
requests = { memory = "2G", cpu = "1" }

  [[relaychain.node_groups]]
  name = "alice"
  args = [ "-lparachain=debug" ]
  count = 9

  [[relaychain.node_groups]]
  name = "bob"
  command = "kagome"
  prometheus_prefix = "kagome"
  args = [ "-lparachain=debug", "--wasm-execution Compiled" ]
  count = 3

[[parachains]]
id = 2000
addToGenesis = true
genesis_state_generator = "undying-collator export-genesis-state --pov-size=100000 --pvf-complexity=1"

  [parachains.collator]
  name = "collator01"
  command = "undying-collator"
  args = ["-lparachain=debug", "--pov-size=100000", "--pvf-complexity=1", "--parachain-id=2000"]

[[parachains]]
id = 2001
cumulus_based = true

  [parachains.collator]
  name = "collator02"
  command = "polkadot-parachain"
  args = ["-lparachain=debug"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"