name: Enhancement for KAGOME
description: Suggest an improvement to an existing feature in the KAGOME project.
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the enhancement that you are proposing for the KAGOME project.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Explain why this enhancement is beneficial
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Are you planning to do it yourself in a pull request ?
      description: Any contribution is greatly appreciated. We are more than happy to provide help on the process.
      options:
        - "Yes"
        - "No"
        - Maybe
    validations:
      required: true