FROM alpine AS kagome_build_environment
MAINTAINER Dmitriy Khaustov aka xDimon (khaustov.dm@gmail.com)

# Install dependesciee
RUN apk add bash openssh-client python3 perl rust cargo git cmake make g++ ccache linux-headers

# Setup python
RUN \
    if [[ ! -e /usr/bin/pip ]]; then ln -s /usr/bin/pip3 /usr/bin/pip; fi && \
    if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
	python -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip install --upgrade pip setuptools && \
	pip install requests && \
	pip install gitpython && \
    rm -r /root/.cache

# Install custom ssh config
COPY .ssh /root/.ssh/

# Initial fetching kagome repo
RUN cd /root && \
	git clone https://github.com/soramitsu/kagome.git && \
	cd /root/kagome && \
	git submodule update --init --recursive

# Dummy for entrypoint
CMD ["/bin/echo", "This is dummy sript. Use kagome.sh for build kagome within this container"]

