FROM alpine:3

# Install dependesciee
RUN apk add --no-cache \
        bash \
        openssh-client \
        python3 \
        perl \
        rust \
        cargo \
        git \
        cmake \
        make \
        g++ \
        ccache \
        linux-headers \
        docker-cli

# Setup python
RUN \
    if [[ ! -e /usr/bin/pip ]]; then ln -s /usr/bin/pip3 /usr/bin/pip; fi && \
    if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
	python -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip install --upgrade pip setuptools && \
	pip install requests && \
	pip install gitpython && \
    rm -r /root/.cache

# ToDo should be fixed in library repo, this fix is work only for github action, you should change home dir
# The imported target "sr25519::sr25519" references the file
#     "/github/home/.hunter/_Base/7819e7d/473f5cb/ee8f669/Install/lib/libsr25519crust.a"
#  but this file does not exist.  Possible reasons include:
RUN mkdir -p /github/home/.hunter/_Base/7819e7d/473f5cb/ee8f669/Install/lib && \
 	ln -s /github/home/.hunter/_Base/7819e7d/473f5cb/ee8f669/Install/lib64/libsr25519crust.a /github/home/.hunter/_Base/7819e7d/473f5cb/ee8f669/Install/lib/libsr25519crust.a
