FROM alpine:3

# Install dependesciee
RUN apk add --no-cache \
        bash \
        openssh-client \
        python3 \
        perl \
        rust \
        cargo \
        git \
        cmake \
        make \
        g++ \
        ccache \
        linux-headers \
        docker-cli \
        tar

# Setup python
RUN \
    if [[ ! -e /usr/bin/pip ]]; then ln -s /usr/bin/pip3 /usr/bin/pip; fi && \
    if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
	python -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip install --upgrade pip setuptools && \
	pip install requests && \
	pip install gitpython && \
    rm -r /root/.cache
