[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  args = [ "-lruntime=debug,parachain=trace" ]
  command = "kagome"
  prometheus_prefix = "kagome"

  [[relaychain.nodes]]
  name = "bob"
  args = [ "-lruntime=debug,parachain=trace" ]
  command = "kagome"
  prometheus_prefix = "kagome"

[[parachains]]
id = 100
add_to_genesis = false

  [parachains.collator]
  name = "collator01"
  command = "adder-collator"
  args = [ "-lruntime=debug,parachain=trace" ]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
