[settings]
timeout = 1000
bootnode = false

[relaychain]
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"
  command = "kagome"
  prometheus_prefix = "kagome"


[[parachains]]
id = 100
add_to_genesis = true

  [[parachains.collators]]
    name = "collator-1"
    command = "polkadot-parachain"
    args = ["-lparachain=debug"]

  [[parachains.collators]]
    name = "collator-2"
    command = "polkadot-parachain"
    args = ["-lparachain=debug"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
