[settings]
timeout = 1000
bootnode = true

[relaychain]
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"
  command = "kagome"
  prometheus_prefix = "kagome"

[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  command = "polkadot-parachain"
