[settings]
timeout = 1000
bootnode = true

[relaychain]
default_image = "docker.io/parity/polkadot:latest"
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob" ]
  command = "kagome"
  image = "soramitsu/kagome:latest"
  prometheus_prefix = "kagome"

[[parachains]]
id = 100

  [parachains.collator]
  name = "collator01"
  image = "docker.io/parity/polkadot-parachain:latest"
  command = "polkadot-parachain"
