{
 "title": "Kagome | Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(kagome_build_info{}) by (name, chain, version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The roles the node is running as",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kagome_node_roles{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Is Parachain Validator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kagome_node_is_parachain_validator{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is Active Validator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kagome_node_is_active_validator{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Major Syncing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kagome_sub_libp2p_is_major_syncing{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version and restarts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "kagome_build_info{}", "legendFormat": "{{version}} ({{instance}})" }
   ]
  },
  { "title": "Node metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kagome_process_start_time_seconds{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - kagome_process_start_time_seconds{}",
     "legendFormat": "uptime"
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Block height info of the chain best",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kagome_block_height{status=\"best\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block height info of the chain finalized",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kagome_block_height{status=\"finalized\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Difference between best and finalized blocks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kagome_block_height{status=\"best\"} - scalar(kagome_block_height{status=\"finalized\"}))",
     "legendFormat": "difference"
    }
   ]
  },
  {
   "title": "Major Syncing",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "expr": "kagome_sub_libp2p_is_major_syncing{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block height info of the chain best",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "kagome_block_height{status=\"best\"}",
     "legendFormat": "chain best"
    }
   ]
  },
  {
   "title": "Block height info of the chain finalized",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "kagome_block_height{status=\"finalized\"}",
     "legendFormat": "chain finalized"
    }
   ]
  },
  {
   "title": "Difference between best and finalized blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "kagome_block_height{status=\"best\"} - scalar(kagome_block_height{status=\"finalized\"})",
     "legendFormat": "difference"
    }
   ]
  },
  {
   "title": "Rate of new blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "1/rate(kagome_block_height{status=\"finalized\"}[5m])",
     "legendFormat": "rate_of_new_blocks"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Highest GRANDPA round",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "kagome_finality_grandpa_round{}",
     "legendFormat": "kagome_finality_grandpa_round"
    }
   ]
  },
  {
   "title": "Number of peers we sync with",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 31 },
   "targets": [
    { "expr": "kagome_sync_peers{}", "legendFormat": "kagome_sync_peers" }
   ]
  },
  {
   "title": "Number of known chain leaves (aka forks)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 31 },
   "targets": [
    { "expr": "sum(kagome_number_leaves{})", "legendFormat": "forks" }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Number of actual persistent RPC sessions ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(kagome_rpc_sessions_opened{} - kagome_rpc_sessions_closed{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of persistent RPC sessions opened",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 40 },
   "targets": [
    {
     "expr": "sum(kagome_rpc_sessions_opened{})",
     "legendFormat": "opened"
    }
   ]
  },
  {
   "title": "Number of persistent RPC sessions closed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 40 },
   "targets": [
    {
     "expr": "sum(kagome_rpc_sessions_closed{})",
     "legendFormat": "closed"
    }
   ]
  },
  { "title": "Parachain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Parachain candidate disputes votes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kagome_parachain_candidate_dispute_votes{validity=\"valid\"})",
     "legendFormat": "valid"
    },
    {
     "expr": "sum(kagome_parachain_candidate_dispute_votes{validity=\"invalid\"})",
     "legendFormat": "invalid"
    }
   ]
  },
  {
   "title": "Is parachain validator",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "kagome_node_is_parachain_validator{}",
     "legendFormat": "kagome_node_is_parachain_validator"
    }
   ]
  },
  {
   "title": "Parachain availability recovery",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 47 },
   "targets": [
    {
     "expr": "sum(kagome_parachain_availability_recovery_recoveries_started{})",
     "legendFormat": "recoveries started"
    },
    {
     "expr": "sum(kagome_parachain_availability_recovery_recoveries_finished{})",
     "legendFormat": "recoveries finished"
    }
   ]
  },
  {
   "title": "Parachain candidate disputes votes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(kagome_parachain_candidate_dispute_votes{validity=\"valid\"})",
     "legendFormat": "valid"
    },
    {
     "expr": "sum(kagome_parachain_candidate_dispute_votes{validity=\"invalid\"})",
     "legendFormat": "invalid"
    }
   ]
  },
  {
   "title": "Is active validator",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "kagome_node_is_active_validator{}",
     "legendFormat": "kagome_node_is_active_validator"
    }
   ]
  },
  {
   "title": "Parachain candidate disputes total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum(kagome_parachain_candidate_disputes_total{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Parachain approvals no shows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "targets": [
    {
     "expr": "sum(kagome_parachain_approvals_no_shows_total{})",
     "legendFormat": "kagome_parachain_approvals_no_shows_total"
    }
   ]
  },
  {
   "title": "Parachain finality disputes lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "targets": [
    {
     "expr": "sum (kagome_parachain_disputes_finality_lag{})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Buckets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "PVF execution time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(kagome_pvf_execution_time_bucket{}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block verification and import",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(kagome_block_verification_and_import_time_bucket{}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Proposer block constructed",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(kagome_proposer_block_constructed_bucket{}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "PVF preparation time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum(increase(kagome_pvf_preparation_time_bucket{}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Parachain candidate validation code",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 74 },
   "targets": [
    {
     "expr": "sum(increase(kagome_parachain_candidate_validation_code_size_bucket{}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Backed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Backed Candidates In Block ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(kagome_node_backed_candidates_in_block{})",
     "legendFormat": "kagome_node_backed_candidates_in_block"
    }
   ]
  },
  {
   "title": "Include Candidates In Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 83 },
   "targets": [
    {
     "expr": "kagome_node_include_candidates_in_block{}",
     "legendFormat": "kagome_node_include_candidates_in_block"
    }
   ]
  },
  {
   "title": "No Backed Candidates In Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 83 },
   "targets": [
    {
     "expr": "kagome_node_no_backed_candidates_in_block{}",
     "legendFormat": "kagome_node_no_backed_candidates_in_block"
    }
   ]
  },
  {
   "title": "No Include Candidates In Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "kagome_node_no_include_candidates_in_block{}",
     "legendFormat": "kagome_node_no_include_candidates_in_block"
    }
   ]
  },
  {
   "title": "No Backed No Include Candidates In Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "targets": [
    {
     "expr": "kagome_node_no_backed_no_include_candidates_in_block{}",
     "legendFormat": "kagome_node_no_backed_no_include_candidates_in_block"
    }
   ]
  },
  {
   "title": "Total number of blocks produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "targets": [
    { "expr": "kagome_node_total_blocks{}", "legendFormat": "kagome_node_total_blocks" }
   ]
  }
 ]
}