[settings]
enable_tracing = false

[relaychain]
default_command = "polkadot"
chain_spec_path = "kagome/zombienet/0010-validators-warp-sync/gen-db-raw.json"
chain = "gen-db"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  args = ["--sync warp"]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  command = "kagome"
  prometheus_prefix = "kagome"
  args = ["--sync Warp"]

  #we need at least 3 nodes for warp sync
  [[relaychain.nodes]]
  name = "charlie"
  validator = false
  db_snapshot = "https://www.googleapis.com/drive/v3/files/12T_sO7BGc3aRNw8aMIZDf36bO6HUsEgY?alt=media&key=AIzaSyB-qssH0qmtahNKJf_T6iMZMs-9SkColu8"

  [[relaychain.nodes]]
  name = "dave"
  validator = false
  db_snapshot = "https://www.googleapis.com/drive/v3/files/12T_sO7BGc3aRNw8aMIZDf36bO6HUsEgY?alt=media&key=AIzaSyB-qssH0qmtahNKJf_T6iMZMs-9SkColu8"

  [[relaychain.nodes]]
  name = "eve"
  validator = false
  db_snapshot = "https://www.googleapis.com/drive/v3/files/12T_sO7BGc3aRNw8aMIZDf36bO6HUsEgY?alt=media&key=AIzaSyB-qssH0qmtahNKJf_T6iMZMs-9SkColu8"

