if(ASAN)
  print("Address Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_address.cmake)
endif()
if(LSAN)
  print("Leak Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_leak.cmake)
endif()
if(MSAN)
  print("Memory Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_memory.cmake)
endif()
if(TSAN)
  print("Thread Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_thread.cmake)
endif()
if(UBSAN)
  print("Undefined Behavior Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/toolchain/flags/sanitize_undefined.cmake)
endif()
