[settings]
timeout = 1000
bootnode = false

[relaychain]
chain = "rococo-local"
command = "polkadot"

[relaychain.genesis.runtimeGenesis.patch.configuration.config]
  needed_approvals = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.scheduler_params]
  max_validators_per_core = 2

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice" ]

  [[relaychain.nodes]]
  name = "bob"
  command = "kagome"
  args = [ "--bob" ]
  prometheus_prefix = "kagome"

[[parachains]]
id = 100
addToGenesis = true

  [[parachains.collators]]
    name = "collator-1"
    command = "polkadot-parachain"
    args = ["-lparachain=debug"]

  [[parachains.collators]]
    name = "collator-2"
    command = "polkadot-parachain"
    args = ["-lparachain=debug"]

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
