name: Autotests

on:
  repository_dispatch:
    types: [ autotests ]

jobs:
  autotests:
    runs-on: ubuntu-latest
    container: soramitsu/kagome-autotests:1.0
    steps:
      - name: Run autotests
        working-directory: /kagome-autotests
        run: python3 -m pytest --alluredir=./allure_reports
        shell: sh
    env:
      KAGOME_S1: ${{ secrets.KAGOME_S1 }}
      SUBSTRATE_S2: ${{ secrets.SUBSTRATE_S2 }}
      BOB: ${{ secrets.BOB }}
