  on:
    workflow_dispatch: 
      
  jobs:
    build_and_push_minideb_base:
      runs-on: [ actions-runner-controller ]
      timeout-minutes: 120
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            tags: qdrvm/kagome-minideb:${{ github.run_number }}, qdrvm/kagome-minideb:latest
            file: ./housekeeping/docker/kagome-dev/minideb.Dockerfile
            #context: .
            push: true
            